spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true